### Spring Security & OAuth2
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 153689546576-0cgf677hv07vsp3m21eeqq30bprs8iur.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
