spring:
  datasource:
    generate-unique-name: false

  ### auto reload when it's being developed
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  ### execute schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true

  ### H2 inmemory Database
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:

  session:
    store-type: jdbc

  ### Spring Security & OAuth2 setting file
  profiles:
    include: oauth

  ### error stack trace
  server.error:
    include-exception: true
    include-stacktrace: never # not include stacktrace contents in error message
    whitelabel.enabled: false # not use white error page

