spring:
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driver-class-name:
      url: jdbc:h2:mem:testdb
      username: sa
      password:

  config:
    activate:
      on-profile: oauth

  session:
    store-type: jdbc
